service: import-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

  environment:
    ENV_STAGE: dev
    S3_BUCKET_NAME: 'my-store-app-import-vks'
    SQS_QUEUE_NAME: CatalogItemsQueue

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*
            - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:GetQueueUrl
            - sqs:ReceiveMessage
          Resource:
            - arn:aws:sqs:${self:provider.region}:*:${self:provider.environment.SQS_QUEUE_NAME}

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    memorySize: 128
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            arn: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:authorization-service-dev-basicAuthorizer
            type: request
            resultTtlInSeconds: 0  # Optional: Cache duration

  importFileParser:
    handler: handler.importFileParser
    memorySize: 128
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

